apiVersion: v1
kind: Secret
metadata:
  name: influx-auth
  namespace: monitoring
type: Opaque
stringData:
  INFLUXDB_ADMIN_USER: admin
  INFLUXDB_ADMIN_PASSWORD: admin123
  INFLUXDB_DB: k6
  INFLUXDB_URL: influxdb.monitoring.svc.cluster.local:8086
  #  # canonical keys used by Grafana and k6 job
  #  username: admin
  #  password: supersecret123
  #  database: k6
  #  # leave URL without credentials (Grafana will add creds from env)
  #  url: http://influxdb.monitoring.svc.cluster.local:8086



